#!/bin/bash
# acronym: git g[itops] pr l[ist]

exclusions='["show-diff", "dependencies"]'

gh pr list \
    --repo 'Engineering-TFIN/gitops' \
    --json labels,reviews,title,url |\
    jq \
        -r \
        --arg nullLabel "-" \
        --argjson exclusions "${exclusions}" \
        '.[] | "\(.url)|[\(.reviews[] | .state)]|\([.labels[] | .name] - $exclusions | .[] // $nullLabel)|\(.title)"' |\
    sort -t'|' -k4 -k3 |\
    sed -E \
        -e 's/APPROVED/✅/g' \
        -e 's/CHANGES_REQUESTED/❌/g' \
        -e 's/COMMENTED/💬/g' \
        -e 's/\[DEVOPS-1094\] Update( Helm release)?/.../' |\
    column -s'|' -t
