#!/bin/bash

# Copyright (C) 2023 Hefeweizen (https://github.com/Hefeweizen)
# Permission to copy and modify is granted under the Apace License 2.0

# git wip - make a wip commit to capture intermediate changes


# if env var found, then abort saving wip
#
# This was specifically added to have git not interfere
# with --interactive patching/rebasing.
# ```
# $ g config core.editor
# NO_GIT_WIP=1 vim
# ```
if [[ ${NO_GIT_WIP} -eq 1 ]]; then
    exit
fi

current_branch_name=$(git rev-parse --abbrev-ref HEAD)
wip_branch="refs/heads/${current_branch_name}-wip"

git stash store "$(git stash create)" -m "${wip_branch} from git-wip" # though the message is unlikely to ever be seen

# updates or creates
git update-ref "${wip_branch}" "stash@{0}"

git stash drop --quiet
