#!/bin/bash
# acronym: git pr l[ist]
#
# argument handling is very hackish, switch to python?

if [[ -z ${1} ]]; then
    # nothing specified, use current
    repo=$(gh repo view --json nameWithOwner -q ".nameWithOwner")
else
    repo="Engineering-TFIN/${1}"
    shift
fi
# any additional args found are passed directly to `gh`

exclusions='["show-diff", "dependencies"]'

gh pr list \
    --repo "${repo}" \
    "$@" \
    --json labels,reviews,title,url |\
    jq \
        -r \
        --arg nullLabel "-" \
        --argjson exclusions "${exclusions}" \
        '.[] | "\(.url)|\( .reviews | group_by(.author.login) | map(sort_by(.submittedAt)) | [.[] | last | .state ] | join("") |select( . != "") // "-" )|\([.labels[] | .name] - $exclusions | .[] // $nullLabel)|\(.title)"' |\
    sort -t'|' -k4 -k3 |\
    sed -E \
        -e 's/APPROVED/✅/g' \
        -e 's/CHANGES_REQUESTED/❌/g' \
        -e 's/COMMENTED/💬/g' \
        -e 's/DISMISSED/💨/g' \
        -e 's/\[DEVOPS-1094\] Update( Helm release)?/.../' |\
    column -s'|' -t
