#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = [
#   "boto3",
# ]
# ///
"""
base generated by gemini 2.5 Flash on 2025/09/22; some clean-up & rearrangement
"""


import argparse
import sys

import boto3

def parse_args():
    parser = argparse.ArgumentParser(description='Check if tags exist for ECR container images.')

    parser.add_argument(
        'images', 
        nargs='*', # if 0, assumes list from stdin
        help='A list of images to check, in the format <repo>:<tag>'
    )

    return parser.parse_args()


def check_ecr_tags(ecr_client, repository_name, tag):
    """Checks if a specific tag exists in an ECR repository."""
    try:
        response = ecr_client.describe_images(
            repositoryName=repository_name,
            filter={'tagStatus': 'TAGGED'}
        )
        for image in response.get('imageDetails', []):
            if tag in image.get('imageTags', []):
                return True
        return False
    except ecr_client.exceptions.RepositoryNotFoundException:
        print(f"⚠ Repository '{repository_name}' not found.")
        return False
    except Exception as e:
        print(f"An error occurred: {e}")
        # need to fail better if credentials aren't found
        return False

def main():
    args = parse_args()

    ecr_client = boto3.client('ecr')

    if not sys.stdin.isatty():
        # Read image list from stdin
        images = [line.strip() for line in sys.stdin.readlines() if line.strip()]
    else:
        images = args.images

    for image_string in images:
        try:
            repository_name, tag = image_string.split(':', 1)
            is_present = check_ecr_tags(ecr_client, repository_name, tag)
            
            if is_present:
                print(f"✅ Tag '{tag}' is present in repository '{repository_name}'.")
            else:
                print(f"❌ Tag '{tag}' is NOT present in repository '{repository_name}'.")
        except ValueError:
            print(f"❌ Invalid format for image string: '{image_string}'. Expected '<repo>:<tag>'.")
    
if __name__ == "__main__":
    main()
